- block:
  - name: Run apt-get update to get sync
    apt:
      update_cache: yes
  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
  - name: Install ca-certificates
    apt:
      name: ca-certificates
  - name: Install wget
    apt:
      name: wget
  - name: Install dirmngr
    apt:
      name: dirmngr
  - name: Install gnupg
    apt:
      name: gnupg
  - name: Install software-properties-common
    apt:
      name: software-properties-common
  - name: Add AdoptOpenJDK public key
    shell: wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
    args:
      warn: False
  - name : Add the AdoptOpenJDK APT repository
    shell: add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
  - name: Run apt-get update to get sync
    apt:
      update_cache: yes
  become: yes
- import_tasks: java8.yml
- import_tasks: java11.yml
- import_tasks: java14.yml
- import_tasks: maven.yml
