- block:
  - name: Create install dir
    file:
      path: /opt/idea
      state: directory
      owner: vagrant
      group: vagrant
      mode: '0775'
  - name: Download Intellij Ultimate
    get_url:
      url: https://download.jetbrains.com/idea/ideaIU-2020.1.3.tar.gz
      dest: /opt/idea/idea.tar.gz
      owner: vagrant
      group: vagrant
      mode: '0775'
  - name: Extract Intellij Ultimate
    unarchive:
      src: /opt/idea/idea.tar.gz
      dest: /opt/idea/
      owner: vagrant
      group: vagrant
      mode: '0775'
  become: yes