- block:
  - name: Download & extract Intellij Ultimate
    unarchive:
      src: https://download.jetbrains.com/idea/ideaIU-2020.1.3.tar.gz
      dest: /opt
      remote_src: yes
      owner: vagrant
      group: vagrant
      mode: u=rwx,g=rwx,o=r
  become: yes